package com.master.faez.telbot.state;

public enum USER_STATES {
    START,
    WAITING_FOR_HOME_KEYBOARD_RESPONSE,
    WAITING_FOR_BOOK_KEYBOARD_RESPONSE,
    WAITING_FOR_NEW_BOOK_NAME,
    WAITING_FOR_BOOK_SELECTION,
    WAITING_FOR_SELECTED_BOOK_KEYBOARD_RESPONSE,


}
