package com.master.faez.telbot.state;

public enum USER_STATES {
    START,
    HOME,
    BOOK_MANAGEMENT,
    BOOK_LIST,
    BOOK_CREATE,
    BOOK_EDIT,
    BOOK_DELETE,
    RESOURCE_MANAGEMENT,
    RESOURCE_CREATE,
    RESOURCE_LIST,
    RESOURCE_DELETE,
    RESOURCE_EDIT,
    FILE_MANAGEMENT,
    FILE_ADD,
    FILE_LIST,
    FILE_EDIT,
    FILE_DELETE,
    FILE_SELECT,
    BROADCAST,
    ABOUT_US,
    ADD_ADMIN,
    DELETE_ADMIN,


}
