package com.master.faez.telbot.state;

public enum USER_STATES {
    START,
    HOME,
    BOOK_MANAGEMENT,
    BOOK_KEYBOARD,
    BOOK_CREATE,
    BOOK_EDIT,
    BOOK_DELETE,
    BOOK_LIST_SELECTION,
    RESOURCE_MANAGEMENT,
    RESOURCE_CREATE,
    RESOURCE_SELECT,
    FILE_MANAGEMENT,
    FILE_ADD,
    FILE_LIST,
    FILE_EDIT,
    FILE_DELETE


}
