package com.master.faez.telbot.state;

public enum USER_EVENTS {
    USER_EXISTS_OR_CREATED,
    HOME_KEYBOARD_RESPONSE,
    SELECT_BOOK,
    CREATE_BOOK,
    EDIT_BOOK,
    DELETE_BOOK,
    BOOK_LIST_SELECTED,
    SELECT_RESOURCE,
    CREATE_RESOURCE,
    ADD_FILE,
    LIST_FILES,
    EDIT_FILE,
    DELETE_FILE


}
