package com.master.faez.telbot.state;

public enum USER_EVENTS {
    USER_EXISTS_OR_CREATED,
    SELECT_BOOK,
    BOOK_SELECTED,
    CREATE_BOOK,
    EDIT_BOOK,
    DELETE_BOOK,
    BOOK_LIST_SELECTED,
    SELECT_RESOURCE,
    RESOURCE_SELECTED,
    DELETE_RESOURCE,
    CREATE_RESOURCE,
    ADD_FILE,
    LIST_FILES,
    EDIT_FILE,
    DELETE_FILE,
    FILE_SELECTED,
    BROADCAST,
    ABOUT_US,
    ADD_ADMIN,
    DELETE_ADMIN, RESOURCE_EDIT,



}
